In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
dataset1 = pd.read_excel('Train_dataset.xlsx')
dataset2 = pd.read_excel('Test_dataset.xlsx')
x1 = dataset1.iloc[:, [0,1,11,14]].values
y = dataset1.iloc[:, -1].values
x2 = dataset2.iloc[:, [0,1,11,14]].values


In [3]:
print('Shape x1 is: {}'.format(x1.shape))
print('Shape x2 is: {}'.format(x2.shape))
print('Shape y is: {}'.format(y.shape))

Shape x1 is: (787, 4)
Shape x2 is: (501, 4)
Shape y is: (787,)


In [4]:
print(x2)

[['Tuensang' 'Nagaland' 0.25339010990797806 2769.0]
 ['Lakshmeshwar' 'Karnataka' 0.1925548935336575 636502.0]
 ['Zira' 'Punjab' 0.8878816363537942 242367.0]
 ...
 ['Kedarnath' 'Uttarakhand' 0.7232532805565187 105882.0]
 ['Gangotri' 'Uttarakhand' 0.42106070874521906 105882.0]
 ['Kumarganj' 'Uttar Pradesh' 0.15437496778628979 3104060.0]]


In [5]:
print(x1)

[['Mumbai' 'Maharashtra' 0.7004395374251806 4408916.0]
 ['Delhi' 'Delhi' 0.9200182321815967 2379169.0]
 ['Bangalore' 'Karnataka' 0.09708525131204238 636502.0]
 ...
 ['Mahe' 'Puducherry' 0.06675218008438255 106153.0]
 ['Lanka' 'Assam' 0.6275556340756849 24720.0]
 ['Rudauli' 'Uttar Pradesh' 0.31338326279829554 3104060.0]]


In [6]:
y = y.reshape(len(y),1)


In [7]:
from sklearn.impute import SimpleImputer
imputer1 = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer1.fit(x1[:, 2:4])
x1[:, 2:4] = imputer1.transform(x1[:, 2:4])

In [8]:
print(x1)


[['Mumbai' 'Maharashtra' 0.7004395374251806 4408916.0]
 ['Delhi' 'Delhi' 0.9200182321815967 2379169.0]
 ['Bangalore' 'Karnataka' 0.09708525131204238 636502.0]
 ...
 ['Mahe' 'Puducherry' 0.06675218008438255 106153.0]
 ['Lanka' 'Assam' 0.6275556340756849 24720.0]
 ['Rudauli' 'Uttar Pradesh' 0.31338326279829554 3104060.0]]


In [9]:
imputer2 = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer2.fit(x2[:, 2:4])
x2[:, 2:4] = imputer2.transform(x2[:, 2:4])

In [10]:
print(x2)

[['Tuensang' 'Nagaland' 0.25339010990797806 2769.0]
 ['Lakshmeshwar' 'Karnataka' 0.1925548935336575 636502.0]
 ['Zira' 'Punjab' 0.8878816363537942 242367.0]
 ...
 ['Kedarnath' 'Uttarakhand' 0.7232532805565187 105882.0]
 ['Gangotri' 'Uttarakhand' 0.42106070874521906 105882.0]
 ['Kumarganj' 'Uttar Pradesh' 0.15437496778628979 3104060.0]]


In [11]:
print('Shape x1 is: {}'.format(x1.shape))
print('Shape x2 is: {}'.format(x2.shape))
print('Shape y is: {}'.format(y.shape))

Shape x1 is: (787, 4)
Shape x2 is: (501, 4)
Shape y is: (787, 1)


In [12]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
x1[:, 0] = labelencoder.fit_transform(x1[:, 0])
x1[:, 1] = labelencoder.fit_transform(x1[:, 1])

In [13]:
labelencoder = LabelEncoder()
x2[:, 0] = labelencoder.fit_transform(x2[:, 0])
x2[:, 1] = labelencoder.fit_transform(x2[:, 1])

In [14]:
print(x1)

[[378 16 0.7004395374251806 4408916.0]
 [135 6 0.9200182321815967 2379169.0]
 [52 13 0.09708525131204238 636502.0]
 ...
 [328 22 0.06675218008438255 106153.0]
 [309 2 0.6275556340756849 24720.0]
 [552 30 0.31338326279829554 3104060.0]]


In [15]:
print(x2)

[[450 19 0.25339010990797806 2769.0]
 [69 12 0.1925548935336575 636502.0]
 [495 21 0.8878816363537942 242367.0]
 ...
 [55 27 0.7232532805565187 105882.0]
 [42 27 0.42106070874521906 105882.0]
 [63 26 0.15437496778628979 3104060.0]]


In [16]:
print('Shape x1 is: {}'.format(x1.shape))
print('Shape x2 is: {}'.format(x2.shape))
print('Shape y is: {}'.format(y.shape))

Shape x1 is: (787, 4)
Shape x2 is: (501, 4)
Shape y is: (787, 1)


In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x1, y)

LinearRegression()

In [18]:
y_pred = regressor.predict(x2)

In [19]:
print(len(x2))
print(len(y_pred))

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), x2[:, :-3]),1)) 
#printing the predicted results first and then the city repectively.

501
501
[[2966.536921726841 450]
 [7657.536725500818 69]
 [2653.390101456491 495]
 ...
 [4853.521950400289 55]
 [5087.201781551377 42]
 [11470.582109244826 63]]


In [20]:
y_pred

array([[ 2966.54],
       [ 7657.54],
       [ 2653.39],
       [12282.16],
       [ 8855.86],
       [ 5979.53],
       [13919.7 ],
       [ 3526.7 ],
       [ 6676.29],
       [ 7397.08],
       [ 7382.96],
       [14297.91],
       [ 6376.73],
       [ 5924.25],
       [12444.69],
       [ 5088.94],
       [ 7111.56],
       [ 5261.14],
       [ 7056.88],
       [ 5115.57],
       [ 5481.56],
       [ 6134.15],
       [ 3736.22],
       [12289.81],
       [ 6944.71],
       [ 7623.74],
       [12109.33],
       [10306.07],
       [ 2375.16],
       [ 6023.24],
       [ 4530.54],
       [ 6840.14],
       [ 6826.18],
       [14141.65],
       [13931.29],
       [ 4699.91],
       [ 8458.12],
       [ 7989.41],
       [ 6686.08],
       [ 8736.43],
       [12063.27],
       [14483.32],
       [ 4884.55],
       [ 4433.32],
       [ 5284.58],
       [ 5211.35],
       [ 6225.33],
       [ 7322.31],
       [ 5275.85],
       [12499.57],
       [ 4397.15],
       [ 6183.41],
       [ 803

In [21]:
final = y_pred.flatten()

In [22]:
print(final)


[ 2966.54  7657.54  2653.39 12282.16  8855.86  5979.53 13919.7   3526.7
  6676.29  7397.08  7382.96 14297.91  6376.73  5924.25 12444.69  5088.94
  7111.56  5261.14  7056.88  5115.57  5481.56  6134.15  3736.22 12289.81
  6944.71  7623.74 12109.33 10306.07  2375.16  6023.24  4530.54  6840.14
  6826.18 14141.65 13931.29  4699.91  8458.12  7989.41  6686.08  8736.43
 12063.27 14483.32  4884.55  4433.32  5284.58  5211.35  6225.33  7322.31
  5275.85 12499.57  4397.15  6183.41  8033.41  4285.2   4763.05  6909.29
 10342.33  7671.05  2268.07 12842.63  7197.23 14443.94  5927.9   6441.91
  7290.83  8414.96  6351.55 13816.84  9078.82  4031.42  5468.07 10376.71
 11549.73  4665.14  7556.43  2080.68  7250.3  14309.01  6022.79  4775.27
 13127.72  7031.66  5465.7   7517.11 12167.72  5344.7   6038.32  5376.47
  9227.68  4470.    6314.27  8611.53  6756.49  4909.77  9438.45 12621.04
  5956.59 12341.97  8315.52  5601.66  5434.87 13838.62 14151.64  9698.02
  4997.52 12770.89  6114.31  5605.39  5487.97  5969.